version: '3'

services:
  bot:
    container_name: bot
    build: bot/
    depends_on:
      - db
    environment: 
      - TOKEN=6314857373:AAGE5dA5QHejibrBOJlnBPpaQkSoIKNsr9s
    restart: always
    command:  python3 /bot/main.py

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./db_data:/docker-entrypoint-initdb.d
    expose:
      - '5432'
    restart: always